# Generated by Django 2.1.15 on 2021-05-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributosprocesoscorporativos',
            fields=[
                ('atribproccorpnom',
                 models.CharField(db_column='AtribProcCorpNom', max_length=50, primary_key=True, serialize=False)),
                ('atribproccorpiddb', models.IntegerField(db_column='AtribProcCorpIdDB')),
            ],
            options={
                'db_table': 'AtributosProcesosCorporativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caracteristicasmetrologicas',
            fields=[
                ('idcaractmet', models.AutoField(db_column='IdCaractMet', primary_key=True, serialize=False)),
                ('caractmeterrmax', models.FloatField(blank=True, db_column='CaractMetErrMax', null=True)),
                ('caractmetres', models.FloatField(blank=True, db_column='CaractMetRes', null=True)),
                ('caractmetesperrmax', models.IntegerField(blank=True, db_column='CaractMetEspErrMax', null=True)),
                ('caractmetindvis', models.BooleanField(blank=True, db_column='CaractMetIndVis', null=True)),
                ('caractmettipoindvis',
                 models.CharField(blank=True, db_column='CaractMetTipoIndVis', max_length=50, null=True)),
                ('caractmetcantdivi', models.IntegerField(blank=True, db_column='CaractMetCantDivi', null=True)),
                ('caractmetriddb', models.IntegerField(db_column='CaractMetrIdDB')),
            ],
            options={
                'db_table': 'CaracteristicasMetrologicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('cargonom', models.CharField(db_column='CargoNom', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriasinstrumentos',
            fields=[
                ('catinstnom',
                 models.CharField(db_column='CatInstNom', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CategoriasInstrumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriasusos',
            fields=[
                (
                'catusonom', models.CharField(db_column='CatUsoNom', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CategoriasUsos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centrocosto',
            fields=[
                ('centrocostonom',
                 models.CharField(db_column='CentroCostoNom', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CentroCosto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('idcert', models.AutoField(db_column='IdCert', primary_key=True, serialize=False)),
                ('certno', models.CharField(db_column='CertNo', max_length=50)),
                ('certtipo', models.CharField(db_column='CertTipo', max_length=50)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('resultado', models.CharField(blank=True, db_column='Resultado', max_length=50, null=True)),
                ('certfecha', models.DateField(blank=True, db_column='CertFecha', null=True)),
            ],
            options={
                'db_table': 'Certificados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condicionesambientales',
            fields=[
                ('idcondamb', models.AutoField(db_column='IdCondAmb', primary_key=True, serialize=False)),
                ('condambnom', models.CharField(db_column='CondAmbNom', max_length=50)),
            ],
            options={
                'db_table': 'CondicionesAmbientales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Controlmetrologicosistemascadenasmedida',
            fields=[
                ('idcontmetsistcadmed',
                 models.AutoField(db_column='IdContMetSistCadMed', primary_key=True, serialize=False)),
                ('contmetfechaplan', models.DateField(blank=True, db_column='ContMetFechaPlan', null=True)),
                ('contmetfechaejec', models.DateField(blank=True, db_column='ContMetFechaEjec', null=True)),
                ('contmetresultado',
                 models.CharField(blank=True, db_column='ContMetResultado', max_length=50, null=True)),
                ('contmetobservaciones', models.TextField(blank=True, db_column='ContMetObservaciones', null=True)),
            ],
            options={
                'db_table': 'ControlMetrologicoSistemasCadenasMedida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('idemp', models.AutoField(db_column='IdEmp', primary_key=True, serialize=False)),
                ('empcod', models.CharField(blank=True, db_column='EmpCod', max_length=50, null=True)),
                ('empnom', models.TextField(blank=True, db_column='EmpNom', null=True)),
                ('empnomcom', models.CharField(blank=True, db_column='EmpNomCom', max_length=50, null=True)),
                ('empdir', models.CharField(blank=True, db_column='EmpDir', max_length=50, null=True)),
                ('emprepres', models.CharField(blank=True, db_column='EmpRepres', max_length=50, null=True)),
                ('emptelef', models.CharField(blank=True, db_column='EmpTelef', max_length=50, null=True)),
                ('empfax', models.CharField(blank=True, db_column='EmpFax', max_length=50, null=True)),
                ('empemail', models.CharField(blank=True, db_column='EmpEmail', max_length=50, null=True)),
                ('empweb', models.CharField(blank=True, db_column='EmpWeb', max_length=50, null=True)),
                ('empiddb', models.IntegerField(db_column='EmpIdDB')),
            ],
            options={
                'db_table': 'Empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresasserviciadoras',
            fields=[
                ('idempserv', models.AutoField(db_column='IdEmpServ', primary_key=True, serialize=False)),
                ('empservnom', models.CharField(blank=True, db_column='EmpServNom', max_length=50, null=True)),
                ('empservnomcom', models.CharField(blank=True, db_column='EmpServNomCom', max_length=50, null=True)),
                ('empserviddb', models.IntegerField(db_column='EmpServIdDB')),
            ],
            options={
                'db_table': 'EmpresasServiciadoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadosinstrumentos',
            fields=[
                ('estadoinstnom',
                 models.CharField(db_column='EstadoInstNom', max_length=50, primary_key=True, serialize=False)),
                ('estadoinstiddb', models.IntegerField(db_column='EstadoInstIdDB')),
            ],
            options={
                'db_table': 'EstadosInstrumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gruposmagnitudes',
            fields=[
                (
                'grpmagnom', models.CharField(db_column='GrpMagNom', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GruposMagnitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('idinst', models.AutoField(db_column='IdInst', primary_key=True, serialize=False)),
                ('instnom', models.CharField(blank=True, db_column='InstNom', max_length=50, null=True)),
                ('instdescripcion', models.TextField(blank=True, db_column='InstDescripcion', null=True)),
                ('instmarca', models.CharField(blank=True, db_column='InstMarca', max_length=50, null=True)),
                ('instmodelo', models.CharField(blank=True, db_column='InstModelo', max_length=50, null=True)),
                ('instnoserie', models.CharField(blank=True, db_column='InstNoSerie', max_length=50, null=True)),
                ('instnoinv', models.CharField(blank=True, db_column='InstNoInv', max_length=50, null=True)),
                ('instanhofab', models.CharField(blank=True, db_column='InstA�oFab', max_length=50, null=True)),
                ('instpais', models.CharField(blank=True, db_column='InstPais', max_length=50, null=True)),
                ('instindvisual', models.CharField(blank=True, db_column='InstIndVisual', max_length=50, null=True)),
                ('instfechapuestoserv', models.DateField(blank=True, db_column='InstFechaPuestoServ', null=True)),
                ('instreqcal', models.BooleanField(blank=True, db_column='InstReqCal', null=True)),
                ('instperiodocal', models.IntegerField(blank=True, db_column='InstPeriodoCal', null=True)),
                ('instfechacal', models.DateField(blank=True, db_column='InstFechaCal', null=True)),
                ('instreqver', models.BooleanField(blank=True, db_column='InstReqVer', null=True)),
                ('instperiodover', models.IntegerField(blank=True, db_column='InstPeriodoVer', null=True)),
                ('instfechaver', models.DateField(blank=True, db_column='InstFechaVer', null=True)),
                ('instespanel', models.BooleanField(blank=True, db_column='InstEsPanel', null=True)),
                ('instancho', models.FloatField(blank=True, db_column='InstAncho', null=True)),
                ('instlargo', models.FloatField(blank=True, db_column='InstLargo', null=True)),
                ('instalto', models.FloatField(blank=True, db_column='InstAlto', null=True)),
                ('instescircular', models.BooleanField(blank=True, db_column='InstEsCircular', null=True)),
                ('instradio', models.FloatField(blank=True, db_column='InstRadio', null=True)),
                ('instreqcompint', models.BooleanField(blank=True, db_column='InstReqCompInt', null=True)),
                ('instiddb', models.IntegerField(db_column='InstIdDB')),
            ],
            options={
                'db_table': 'Instrumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('lugarmov', models.CharField(db_column='LugarMov', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Lugares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magnitudes',
            fields=[
                ('idmag', models.AutoField(db_column='IdMag', primary_key=True, serialize=False)),
                ('magnom', models.CharField(db_column='MagNom', max_length=50)),
                ('magiddb', models.IntegerField(db_column='MagIdDB')),
            ],
            options={
                'db_table': 'Magnitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodoscalibracionverificacion',
            fields=[
                ('idmetodo', models.AutoField(db_column='IdMetodo', primary_key=True, serialize=False)),
                ('metodonombre', models.CharField(db_column='MetodoNombre', max_length=50)),
                ('metodonorm', models.CharField(db_column='MetodoNorm', max_length=50)),
            ],
            options={
                'db_table': 'MetodosCalibracionVerificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('idmun', models.AutoField(db_column='IdMun', primary_key=True, serialize=False)),
                ('munnom', models.CharField(blank=True, db_column='MunNom', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idemp', models.IntegerField(blank=True, db_column='IdEmp', null=True)),
                ('usernom', models.CharField(blank=True, db_column='UserNom', max_length=50, null=True)),
                ('userperm', models.CharField(blank=True, db_column='UserPerm', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('idplan', models.AutoField(db_column='IdPlan', primary_key=True, serialize=False)),
                ('fechaplan', models.DateField(blank=True, db_column='FechaPlan', null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('planesiddb', models.IntegerField(db_column='PlanesIdDB')),
            ],
            options={
                'db_table': 'Planes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planmantenimiento',
            fields=[
                ('idplan', models.IntegerField(db_column='IdPlan', primary_key=True, serialize=False)),
                ('fechaplan', models.DateField(blank=True, db_column='FechaPlan', null=True)),
                ('fechaejec', models.DateField(blank=True, db_column='FechaEjec', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('planmttoiddb', models.IntegerField(db_column='PlanMttoIdDB')),
            ],
            options={
                'db_table': 'PlanMantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procesoscorporativos',
            fields=[
                ('proccorpnom',
                 models.CharField(db_column='ProcCorpNom', max_length=50, primary_key=True, serialize=False)),
                ('proccorpiddb', models.IntegerField(db_column='ProcCorpIdDB')),
            ],
            options={
                'db_table': 'ProcesosCorporativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('idprov', models.AutoField(db_column='IdProv', primary_key=True, serialize=False)),
                ('provnom', models.CharField(blank=True, db_column='ProvNom', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rangosmedicion',
            fields=[
                ('idrngmed', models.AutoField(db_column='IdRngMed', primary_key=True, serialize=False)),
                ('rngmedlimsup', models.CharField(blank=True, db_column='RngMedLimSup', max_length=50, null=True)),
                ('rngmedliminf', models.CharField(blank=True, db_column='RngMedLimInf', max_length=50, null=True)),
                ('rngmediddb', models.IntegerField(db_column='RngMedIdDB')),
            ],
            options={
                'db_table': 'RangosMedicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relacionatributosprocesos',
            fields=[
                ('idrelatribproccorp',
                 models.AutoField(db_column='IdRelAtribProcCorp', primary_key=True, serialize=False)),
                ('relatribprociddb', models.IntegerField(db_column='RelAtribProcIdDB')),
            ],
            options={
                'db_table': 'RelacionAtributosProcesos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relacionmagnitudesunidadesmedicion',
            fields=[
                ('idrelmagunimed', models.AutoField(db_column='IdRelMagUniMed', primary_key=True, serialize=False)),
                ('relmagunimediddb', models.IntegerField(db_column='RelMagUniMedIdDB')),
            ],
            options={
                'db_table': 'RelacionMagnitudesUnidadesMedicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sealesunificadas',
            fields=[
                ('idsenhalunif', models.IntegerField(db_column='IdSe�alUnif', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Se�alesUnificadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistemascadenasdemedida',
            fields=[
                ('idsistcadmed', models.AutoField(db_column='IdSistCadMed', primary_key=True, serialize=False)),
                ('sistcadmedtipo', models.CharField(blank=True, db_column='SistCadMedTipo', max_length=50, null=True)),
                ('sistcadmednom', models.TextField(blank=True, db_column='SistCadMedNom', null=True)),
                ('sistcadmedperiodocal', models.IntegerField(blank=True, db_column='SistCadMedPeriodoCal', null=True)),
                ('sistcadmedfechacal', models.DateField(blank=True, db_column='SistCadMedFechaCal', null=True)),
            ],
            options={
                'db_table': 'SistemasCadenasDeMedida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocondicionesambientales',
            fields=[
                ('tipocondambnom',
                 models.CharField(db_column='TipoCondAmbNom', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TipoCondicionesAmbientales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadesmedicion',
            fields=[
                ('idunimed', models.AutoField(db_column='IdUniMed', primary_key=True, serialize=False)),
                ('unimedsim', models.CharField(db_column='UniMedSim', max_length=50)),
                ('unimednom', models.CharField(db_column='UniMedNom', max_length=50)),
                ('unimedsi', models.BooleanField(db_column='UniMedSI')),
                ('unimediddb', models.IntegerField(db_column='UniMedIdDB')),
            ],
            options={
                'db_table': 'UnidadesMedicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('usuarionom', models.CharField(db_column='UsuarioNom', max_length=50)),
                ('usuariopassw', models.CharField(db_column='UsuarioPassw', max_length=50)),
                ('usuariotipo', models.CharField(blank=True, db_column='UsuarioTipo', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('idemp',
                 models.ForeignKey(db_column='IdEmp', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                   related_name='idemploc_Empresa', serialize=False, to='corp.Empresas')),
                ('desde', models.DateField(blank=True, db_column='Desde', null=True)),
                ('hasta', models.DateField(blank=True, db_column='Hasta', null=True)),
            ],
            options={
                'db_table': 'Ajustes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cindicionesambientalesinstrumentos',
            fields=[
                ('idcondamb', models.ForeignKey(db_column='IdCondAmb', on_delete=django.db.models.deletion.DO_NOTHING,
                                                primary_key=True, related_name='idcondamb_condicion_ambiental',
                                                serialize=False, to='corp.Condicionesambientales')),
                ('condambinstval', models.FloatField(blank=True, db_column='CondAmbInstVal', null=True)),
            ],
            options={
                'db_table': 'CindicionesAmbientalesInstrumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localizaciones',
            fields=[
                ('idemp',
                 models.ForeignKey(db_column='IdEmp', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                   related_name='idemp_empresa', serialize=False, to='corp.Empresas')),
                ('locnom', models.CharField(db_column='LocNom', max_length=50)),
                ('lociddb', models.IntegerField(db_column='LocIdDB')),
            ],
            options={
                'db_table': 'Localizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('idinst',
                 models.ForeignKey(db_column='IdInst', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                   related_name='idinstmov_instrumento', serialize=False, to='corp.Instrumentos')),
                ('tipomov', models.CharField(blank=True, db_column='TipoMov', max_length=50, null=True)),
                ('comentario', models.TextField(blank=True, db_column='Comentario', null=True)),
            ],
            options={
                'db_table': 'Movimientos',
                'managed': False,
            },
        ),
    ]
