# Generated by Django 2.1.15 on 2021-07-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Señalesunificadas',
            fields=[
                ('idsenhalunif', models.IntegerField(db_column='IdSeñalUnif', primary_key=True, serialize=False)),
                ('senhalunifiddb', models.IntegerField(db_column='SeñalUnifIdDB')),
            ],
            options={
                'db_table': 'SeñalesUnificadas',
                'managed': False,
            },
        ),
    ]
