# Generated by Django 2.1.15 on 2022-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp', '0002_señalesunificadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senhalesunificadas',
            fields=[
                ('idsenhalunif', models.IntegerField(db_column='IdSenhalUnif', primary_key=True, serialize=False)),
                ('senhalunifiddb', models.IntegerField(db_column='SenhalUnifIdDB')),
            ],
            options={
                'db_table': 'SenhalesUnificadas',
                'managed': False,
            },
        ),
    ]
